### ISSUE TITLE
huge parse_string memory leak

### ISSUE THREAD

**Issue by vivision1** [emilk/emilib#15] opened 2022-06-28 19:52 UTC
Hi,
I'm using `Config cfgs = configuru::parse_string(str.c_str(), JSON,"");` on a huge string and after I used it, it keeps on memory after exiting the stack.
Is there a way to solve this?
Thanks

**Comment by emilk** [comment] 2022-07-21 19:10
duplicate of https://github.com/emilk/Configuru/issues/24

**Closed as completed by emilk** 2022-07-21 19:10 UTC
